version: "3.7"
services:
  nrpc:
    build:
      context: ./containers/nrpc
    ports:
      - 8080:80
    networks:
      - poc
    depends_on:
      - bff
  bff:
    build:
      context: ./containers/xyz-bff
    ports:
      - 9080:80
    networks:
      - poc

networks:
  poc:
